"""Private local test identifiers and 30-day retention, independent of legacy reports."""
import json
import fcntl
import secrets
import os
from pathlib import Path
import shutil
import time
from uuid import uuid4

from app.grading.images import SafeImage

RETENTION_SECONDS = 30 * 86400


class ReportStore:
    def __init__(self, directory: str):
        self.root = Path(directory)

    def identity_secret(self) -> bytes:
        """Persist the anonymous test-cookie signer across container restarts."""
        self.root.mkdir(parents=True, exist_ok=True, mode=0o700)
        path = self.root / '.identity-secret'
        descriptor = os.open(path, os.O_RDWR | os.O_CREAT | os.O_NOFOLLOW, 0o600)
        with os.fdopen(descriptor, 'r+b') as stream:
            fcntl.flock(stream, fcntl.LOCK_EX)
            existing = stream.read()
            if not existing:
                existing = secrets.token_bytes(32)
                stream.write(existing)
                stream.flush()
                os.fsync(stream.fileno())
            if len(existing) != 32:
                raise OSError('Invalid private test identity signing file')
            return existing

    def save(self, user_id: str, image_ids: list[str], images: list[SafeImage]) -> None:
        self.root.mkdir(parents=True, exist_ok=True, mode=0o700)
        report_dir = self.root / str(uuid4())
        report_dir.mkdir(mode=0o700)
        try:
            for image_id, image in zip(image_ids, images, strict=True):
                # IDs are generated by our server; callers cannot supply a path.
                if not image_id.startswith('test-image-') or '/' in image_id or '\\' in image_id:
                    raise ValueError('Only server-generated image IDs are allowed')
                path = report_dir / (image_id + '.jpg')
                with path.open('xb') as stream:
                    os.chmod(path, 0o600)
                    stream.write(image.data)
            report = {'user_id': user_id, 'solution_image_ids': image_ids, 'created_at': time.time()}
            path = report_dir / 'report.json'
            with path.open('x', encoding='utf-8') as stream:
                os.chmod(path, 0o600)
                json.dump(report, stream, ensure_ascii=False)
        except BaseException:
            shutil.rmtree(report_dir)
            raise

    def cleanup(self, now: float | None = None) -> None:
        if not self.root.exists():
            return
        cutoff = (time.time() if now is None else now) - RETENTION_SECONDS
        for directory in self.root.iterdir():
            if not directory.is_dir() or directory.is_symlink():
                continue
            path = directory / 'report.json'
            try:
                created = json.loads(path.read_text())['created_at']
                if type(created) not in (int, float):
                    continue
            except (OSError, ValueError, KeyError, TypeError):
                # Remove only abandoned partial writes after the same retention period.
                created = directory.stat().st_mtime
            if created < cutoff:
                shutil.rmtree(directory)
